### ISSUE TITLE
Migrate library to use "Firebase Installations" instead of the now deprecated "Instance ID"

### ISSUE THREAD

**Issue by julioromano** [pusher/push-notifications-android#117]
When using push-notifications-android 1.6.2 with Firebase Cloud Messaging 22.0.0 the library crashes at runtime with:

`java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/firebase/iid/FirebaseInstanceId;
        at com.pusher.pushnotifications.PushNotificationsInstance.start(PushNotificationsInstance.kt:180)
        at com.pusher.pushnotifications.PushNotifications.start(PushNotifications.java:31)`

This is because the Instance ID has been removed from Firebase: https://firebase.google.com/support/release-notes/android#messaging_v22-0-0

The Pusher library must be migrated to make use of Firebase Installations instead of Instance IDs as per: https://firebase.google.com/docs/projects/manage-installations#fid-iid

P.S. A temporary workaround is to explicitly include the `firebase-iid` library as a direct dependency.

**Comment by willc0de4food** [comment]
I'm running into this issue as well, and my app is crashing when I try to register for push notifications.
@julioromano can you add a link to the `firebase-iid` library that you mentioned?

**Comment by Edijae** [comment]
adding firebase bom  to the app gradle file`implementation platform('com.google.firebase:firebase-bom:28.0.1')`(latest version of bom as per this writting was 28.0.1) and you don't have to remember the version of any other firebase library.

```
    implementation platform('com.google.firebase:firebase-bom:28.0.1')
    implementation 'com.google.firebase:firebase-core'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.google.firebase:firebase-iid'
```

**Comment by julioromano** [comment]
@deeborania `firebase-iid` has been removed in firebase bom 31.0.0: https://firebase.google.com/support/release-notes/android#2022-10-12

This library now effectively blocks any upgrades to firebase bom 31.0.0 and above.

Migration to firebase installations is now a priority.

**Comment by julioromano** [comment]
@benjamin-tang-pusher perhaps you can help with prioritizing this task?

**Comment by julioromano** [comment]
@MeenaAlfons can you help?

**Comment by benjamin-tang-pusher** [comment]
I noticed as a workaround for now, you can still add implementation 'implementation 'com.google.firebase:firebase-iid:21.1.0'' and the project will still build.

 implementation 'com.pusher:push-notifications-android:1.9.0'
 implementation 'com.google.firebase:firebase-iid:21.1.0'
 implementation platform('com.google.firebase:firebase-bom:31.0.2')
 implementation 'com.google.firebase:firebase-messaging'

It's not ideal, but until this prioritised by our engineering, this will still fill in the missing dependency for anyone using firebase-bom:31.0.2

**Comment by julioromano** [comment]
Tested and indeed the workaround still works. Thanks.
Needless to say we can't know if/when Google will completely disable `firebase-iid:21.1.0`, so a migration to firebase installations should be put in the roadmap.

**Comment by Oleur** [comment]
Any ETA defined for this fix or not yet? Thanks 😃

**Comment by benjamin-tang-pusher** [comment]
We have a fix here https://github.com/pusher/push-notifications-android/issues/117 but configuring gradle to use a local dependency instead of maven central is very complicated, and I'm still trying to test it.

**Comment by julioromano** [comment]
It seems the fix got released as 1.9.1 but upgrading to that version makes push notifications to stop from working.

**Comment by sebj** [comment]
+1, seeing the same issue as mentioned above. Updating to 1.9.1 and removing our explicit dependency on `firebase-iid` results in no push notifications being delivered.

**Comment by VinuPolly-Bonnet** [comment]
@julioromano @sebj hey guys should we also include `com.google.firebase:firebase-core` in addition to `firebase-iid:21.1.0` when downgrading to `1.9.0` from `1.9.1` for the notifications to work?

**Comment by bhavin-q** [comment]
![image](https://github.com/pusher/push-notifications-android/assets/124991083/2178c5a8-fadb-4ed5-b0a9-82daed69a94f)

Any Update ? I'm still getting this issue

![image](https://github.com/pusher/push-notifications-android/assets/124991083/0e0645b7-9a7d-4c03-9573-c839fbe8da74)
![image](https://github.com/pusher/push-notifications-android/assets/124991083/68dc4985-4817-4fbb-8a89-4419192c2cc9)

**Comment by adriaan** [comment]
+1, this has caused me considerable headaches over the past few days.

I needed to upgrade my Capacitor project to be able to target Android 13 / API level 33 (Play Store requirement from 1 September)
Capacitor 5 requires a version of firebase that no longer includes `firebase-iid`.

It took considerable effort and frustration to find a dependency configuration to satisfy both Capacitor and Pusher.
