### ISSUE TITLE
KotlinReflectionNotSupportedError on app restart

### ISSUE THREAD

**Issue by mbakerinfo** [pusher/push-notifications-android#125]
When an app including this library is restarted while it is running the app crashes from a "KotlinReflectionNotSupportedError"

This can be recreated using Android Studio 2021.1 canary 10 with a new fragment/viewmodel project, 
downgrading to android API 30 to avoid Issue #123.

Using com.google.gms:google-services:4.3.10
com.google.firebase:firebase-messaging:22.0.0
com.google.firebase:firebase-iid:21.1.0
com.pusher:push-notifications-android:1.7.0

Adding in onCreate :
PushNotifications.start(applicationContext, "YOUR_INSTANCE_ID")
PushNotifications.addDeviceInterest("hello")

(and doing all the other normal steps to add pusher to an app)

Hitting run app twice in android studio will recreate the crash.

**Comment by benjamin-tang-pusher** [comment]
Thanks for this, I also get the same in my project. Will try and figure out whats going on.

**Comment by benjamin-tang-pusher** [comment]
This was fixed on the newer version of Android Studio.
