### ISSUE TITLE
Manifest merger android:exported. Apps targeting Android 12 

### ISSUE THREAD

**Issue by ApisitKaewsasan** [pusher/push-notifications-android#126]
Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by philipjan** [comment]
im also experiencing this.

**Comment by hashir1296** [comment]
Experiencing this on my end too. I don't want to risk my userbase by using a  workaround ( overriding the components in my AndroidManifest.xml)

Please fix.

**Comment by benjamin-tang-pusher** [comment]
We're prepping for a new release: #129 and we're going to test it soon.

**Comment by benjamin-tang-pusher** [comment]
We have a `1.8.0-alpha` you can specify in your build.gradle. Please give it a try and let us know how it goes.

**Comment by benjamin-tang-pusher** [comment]
1.8.0 is out now. Please see the changelog for the two issues it fixes.
