### ISSUE TITLE
Which id to use a unique identifier for a push notification

### ISSUE THREAD

**Issue by franciscohanna92** [pusher/push-notifications-android#134]
Hello! 👋🏻 

I'm implemeting a solution to track the status of notifications (sent, received, opened) using the [v1 Webhooks](https://pusher.com/docs/beams/concepts/webhooks/).

I will store information aobut notifications on my own database. Which payload key should I use to track a particular notification? I'm not sure how to decide between `payload.publish_id` or `metadata.event_id` ([here's the example payload format](https://pusher.com/docs/beams/reference/webhooks/#example))

Do you have any official suggestions?

**Comment by benw-pusher** [comment]
Hi! The `publish_id` is used for identification of a push notification so you should use this.
