### ISSUE TITLE
Notifications no longer delivered after updating to 1.9.1

### ISSUE THREAD

**Issue by sebj** [pusher/push-notifications-android#138]
Updating to the latest publicly released version, 1.9.1, of this SDK results in push notifications not being delivered whatsoever when testing on an Android 13 device.

We were previously using version 1.9.0 with an explicit dependency on Firebase IID (`com.google.firebase:firebase-iid:21.1.0`) as per the discussion in #117.
Updating to version 1.9.1, and removing the explicit dependency on Firebase IID results in notifications no longer being delivered when testing (pushing notifications to a specific user ID using the Pusher debug console).

I can reliably reproduce this issue when switching between both versions of Pusher in our app.

**Comment by benjamin-tang-pusher** [comment]
Please use 1.9.0 in the meantime, and don't upgrade to 1.9.1 yet.

**Comment by luibasantes** [comment]
Had the same issue, went back to 1.9.0 and everything worked fine again.

**Comment by benw-pusher** [comment]
We've updated the lib to revert the changes in 1.9.1. 
Please use 1.9.0 or 1.9.2.
