### ISSUE TITLE
`unsubscribeAll` potentially not working

### ISSUE THREAD

**Issue by luismfonseca** [pusher/push-notifications-android#56]
Using the SDK version 1.0.1 and the following code:
```
public void unsubscribeNotifications() {
    PushNotifications.start(getApplicationContext(), Constants.BEAM_INSTANCE_ID);
    PushNotifications.unsubscribe("users."+String.valueOf(DataManager.getInstance().getUserID()));
    PushNotifications.unsubscribeAll();
}
```

We got a customer report that the device was not being unsubscribed from the particular user id, nor from all the others after `PushNotifications.unsubscribeAll()`.

Possible multiple calls to the `PushNotifications.start`?

**Comment by avidenov** [comment]
I have a similar issue, `PushNotifications.unsubscribeAll()` is not working. I also have multiple calls to `PushNotifications.start` 

At the moment I'm using `PushNotifications.unsubscribe(interest)` which is working.

**Comment by julioromano** [comment]
I can confirm `PushNotifications.unsubscribeAll();` is not working on v1.0.1.
I'm calling PushNotifications.start() only once.
Possibly this https://github.com/pusher/push-notifications-android/pull/60 fixes it.
